# RANDOM WALLETS MODE
RANDOM_WALLET = False  # True/False

SLEEP_FROM = 1  # Second
SLEEP_TO = 5  # Second

QUANTITY_THREADS = 1

THREAD_SLEEP_FROM = 5
THREAD_SLEEP_TO = 5

# RETRY MODE
RETRY_COUNT = 3
